# fly.toml app configuration file generated for faunbi-api on 2024-03-30T19:38:38-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'faunbi-api'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
 [http_service.concurrency]
    type = "requests"
    soft_limit = 600
    hard_limit = 700

[[vm]]
  memory = '2048mb'
  cpu_kind = 'shared'
  cpus = 4
